In [66]:
import warnings
warnings.filterwarnings("ignore")
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import numpy as np

from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
data = pd.read_csv(r"/Users/shwetabhat/Desktop/ATML/ProjectTask/DataPrepAndFeatureExt2/PreprocessedNoStopWords.csv")

In [8]:
del data['Content']
del data['id']
data.head(3)


guten_genre                                         clean_data  Book_Name0  \
0    Literary   love seeketh self please bind another delight...         0.0   
1    Literary   james dear james upon time dedicated tale dee...         0.0   
2    Literary   tokyo tijuana gabriele departing america stev...         0.0   

   Book_Name1  Book_Name2  Book_Name3  Book_Name4  Book_Name5  Book_Name6  \
0         0.0         0.0         0.0         0.0         0.0         0.0   
1         0.0         0.0         0.0         0.0         0.0         0.0   
2         0.0         0.0         0.0         0.0         0.0         0.0   

   Book_Name7  ...  Author_Name496  Author_Name497  Author_Name498  \
0         0.0  ...             0.0             0.0             0.0   
1         0.0  ...             0.0             0.0             0.0   
2         0.0  ...             0.0             0.0             0.0   

   Author_Name499  Author_Name500  Author_Name501  Author_Name502  \
0             0.0             0.0             0.0             0.0   
1             0.0             0.0             0.0             0.0   
2             0.0             0.0             0.0             0.0   

   Author_Name503  Author_Name504  Author_Name505  
0             0.0             0.0             0.0  
1             0.0             0.0             0.0  
2             0.0             0.0             0.0  

[3 rows x 1500 columns]

In [4]:
enc1 = OneHotEncoder(handle_unknown='ignore')
enc_df1 = pd.DataFrame(enc1.fit_transform(data[['Book_Name']]).toarray())
 # merge with main df bridge_df on key values
del data['Book_Name']
col_name=[]
for i in range(enc_df1.columns.start,enc_df1.columns.stop,enc_df1.columns.step):
    x="Book_Name"+(str(i))
    col_name.append(x)
enc_df1.columns=col_name
data = data.join(enc_df1)

In [5]:
enc1 = OneHotEncoder(handle_unknown='ignore')
enc_df1 = pd.DataFrame(enc1.fit_transform(data[['Author_Name']]).toarray())
 # merge with main df bridge_df on key values
del data['Author_Name']
col_name=[]
for i in range(enc_df1.columns.start,enc_df1.columns.stop,enc_df1.columns.step):
    x="Author_Name"+(str(i))
    col_name.append(x)
enc_df1.columns=col_name
data = data.join(enc_df1)

In [25]:
labels=data['guten_genre']
cols=list(data.columns)
cols=cols[1:]
data=data[cols]
data

clean_data  Book_Name0  \
0     love seeketh self please bind another delight...         0.0   
1     james dear james upon time dedicated tale dee...         0.0   
2     tokyo tijuana gabriele departing america stev...         0.0   
3     looking back many month struggle foreboding w...         0.0   
4     page last page frontispiece stretched upon ow...         0.0   
..                                                 ...         ...   
989   book pleased bestow especial affection dedica...         0.0   
990   still evening dust hung golden moment slowly ...         0.0   
991   reginald philip graham thursford baron traver...         0.0   
992   bettina mowbray walking deck ocean steamer bo...         0.0   
993   miss heth page vivian paint upon window dwelt...         0.0   

     Book_Name1  Book_Name2  Book_Name3  Book_Name4  Book_Name5  Book_Name6  \
0           0.0         0.0         0.0         0.0         0.0         0.0   
1           0.0         0.0         0.0         0.0         0.0         0.0   
2           0.0         0.0         0.0         0.0         0.0         0.0   
3           0.0         0.0         0.0         0.0         0.0         0.0   
4           0.0         0.0         0.0         0.0         0.0         0.0   
..          ...         ...         ...         ...         ...         ...   
989         0.0         0.0         0.0         0.0         0.0         0.0   
990         0.0         0.0         0.0         0.0         0.0         0.0   
991         0.0         0.0         0.0         0.0         0.0         0.0   
992         0.0         0.0         0.0         0.0         0.0         0.0   
993         0.0         0.0         0.0         0.0         0.0         0.0   

     Book_Name7  Book_Name8  ...  Author_Name496  Author_Name497  \
0           0.0         0.0  ...             0.0             0.0   
1           0.0         0.0  ...             0.0             0.0   
2           0.0         0.0  ...             0.0             0.0   
3           0.0         0.0  ...             0.0             0.0   
4           0.0         0.0  ...             0.0             0.0   
..          ...         ...  ...             ...             ...   
989         0.0         0.0  ...             0.0             0.0   
990         0.0         0.0  ...             0.0             0.0   
991         0.0         0.0  ...             0.0             0.0   
992         0.0         0.0  ...             0.0             0.0   
993         0.0         0.0  ...             0.0             0.0   

     Author_Name498  Author_Name499  Author_Name500  Author_Name501  \
0               0.0             0.0             0.0             0.0   
1               0.0             0.0             0.0             0.0   
2               0.0             0.0             0.0             0.0   
3               0.0             0.0             0.0             0.0   
4               0.0             0.0             0.0             0.0   
..              ...             ...             ...             ...   
989             0.0             0.0             0.0             0.0   
990             0.0             0.0             0.0             0.0   
991             0.0             0.0             0.0             0.0   
992             0.0             0.0             0.0             0.0   
993             0.0             0.0             0.0             0.0   

     Author_Name502  Author_Name503  Author_Name504  Author_Name505  
0               0.0             0.0             0.0             0.0  
1               0.0             0.0             0.0             0.0  
2               0.0             0.0             0.0             0.0  
3               0.0             0.0             0.0             0.0  
4               0.0             0.0             0.0             0.0  
..              ...             ...             ...             ...  
989             0.0             0.0             0.0             0.0  
990             0.0     

In [29]:
X_train, X_test,y_train,y_test = train_test_split(data,labels, test_size=0.3, random_state=42, stratify = labels)

In [33]:
X_train.head(3)

clean_data  Book_Name0  \
330   early june year taking walk hampstead heath f...         0.0   
376   solitary room midnight single candle lighted ...         0.0   
560   sunrise first april appeared suddenly manco c...         0.0   

     Book_Name1  Book_Name2  Book_Name3  Book_Name4  Book_Name5  Book_Name6  \
330         0.0         0.0         0.0         0.0         0.0         0.0   
376         0.0         0.0         0.0         0.0         0.0         0.0   
560         0.0         0.0         0.0         0.0         0.0         0.0   

     Book_Name7  Book_Name8  ...  Author_Name496  Author_Name497  \
330         0.0         0.0  ...             0.0             0.0   
376         0.0         0.0  ...             0.0             0.0   
560         0.0         0.0  ...             0.0             0.0   

     Author_Name498  Author_Name499  Author_Name500  Author_Name501  \
330             0.0             0.0             0.0             0.0   
376             0.0             0.0             0.0             0.0   
560             0.0             0.0             0.0             0.0   

     Author_Name502  Author_Name503  Author_Name504  Author_Name505  
330             0.0             0.0             0.0             0.0  
376             0.0             0.0             0.0             0.0  
560             0.0             0.0             0.0             0.0  

[3 rows x 1499 columns]

In [34]:
vectorizer = TfidfVectorizer(sublinear_tf=True)
train = vectorizer.fit_transform(X_train['clean_data'])
train=pd.DataFrame(train.todense())

In [35]:
test = vectorizer.transform(X_test['clean_data'])
test=pd.DataFrame(test.todense())

In [37]:
train.shape

(695, 114311)

In [62]:
train=X_test.head()

0    1    2    3    4    5    6    7    8    9  ...  Author_Name496  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...             0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...             0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...             0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...             0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...             0.0   

   Author_Name497  Author_Name498  Author_Name499  Author_Name500  \
0             0.0             0.0             0.0             0.0   
1             0.0             0.0             0.0             0.0   
2             0.0             0.0             0.0             0.0   
3             0.0             0.0             0.0             0.0   
4             0.0             0.0             0.0             0.0   

   Author_Name501  Author_Name502  Author_Name503  Author_Name504  \
0             0.0             0.0             0.0             0.0   
1             0.0             0.0             0.0             0.0   
2             0.0             0.0             0.0             0.0   
3             0.0             0.0             0.0             0.0   
4             0.0             0.0             0.0             0.0   

   Author_Name505  
0             0.0  
1             0.0  
2             0.0  
3             0.0  
4             0.0  

[5 rows x 115810 columns]

In [53]:
train.reset_index(drop=True, inplace=True)    
X_train.reset_index(drop=True, inplace=True)

X_train=pd.concat([train,X_train],axis=1)

In [55]:
test.reset_index(drop=True, inplace=True)    
X_test.reset_index(drop=True, inplace=True)

X_test=pd.concat([test,X_test],axis=1)

In [63]:
train=X_train
test=X_test

In [56]:
feature_names = vectorizer.get_feature_names()

In [57]:
len(feature_names)

114311

In [58]:
feature_names

['aachen',
 'aaem',
 'aair',
 'aalsund',
 'aamand',
 'aamy',
 'aamænd',
 'aaoow',
 'aaraaf',
 'aargau',
 'aarhus',
 'aaron',
 'aase',
 'aback',
 'abaddon',
 'abaft',
 'abaho',
 'abaht',
 'abalone',
 'abana',
 'abandon',
 'abandoned',
 'abandonedly',
 'abandoning',
 'abandonment',
 'abanijo',
 'abart',
 'abase',
 'abased',
 'abasement',
 'abash',
 'abashed',
 'abashes',
 'abashing',
 'abashingly',
 'abashment',
 'abasing',
 'abate',
 'abated',
 'abatement',
 'abates',
 'abating',
 'abatis',
 'abatross',
 'abattez',
 'abattis',
 'abattoir',
 'abattre',
 'abawt',
 'abazzia',
 'abbaside',
 'abbassieh',
 'abbate',
 'abbati',
 'abbatial',
 'abbaye',
 'abbe',
 'abbencombe',
 'abberley',
 'abbess',
 'abbetting',
 'abbeville',
 'abbey',
 'abbeyland',
 'abbia',
 'abbie',
 'abbot',
 'abbotsbury',
 'abbotsford',
 'abbott',
 'abbotts',
 'abbozzatore',
 'abbrazza',
 'abbreviate',
 'abbreviated',
 'abbreviating',
 'abbreviation',
 'abbreviative',
 'abbrucia',
 'abby',
 'abbé',
 'abbés',
 'abc',
 'abc

In [64]:
train_labels=y_train
test_labels=y_test 

In [80]:
del train['clean_data']
del test['clean_data']

In [81]:
svc = svm.SVC(gamma='auto')
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}

clf = GridSearchCV(svc, parameters)

clf.fit(train,train_labels)

clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [82]:
predictions=clf.predict(test)
train_pred=clf.predict(train)

print("train accuracy: {} ".format(accuracy_score(train_labels,train_pred,normalize=True, sample_weight=None)))
print("test accuracy: {} ".format(accuracy_score(test_labels,predictions,normalize=True, sample_weight=None))) 


train accuracy: 1.0 
test accuracy: 0.8461538461538461 


In [83]:
print("Confusion Matrix:     ")
print(confusion_matrix(test_labels, predictions))
        
print("\n\nClassification Report:       ")
print(classification_report(test_labels, predictions))

Confusion Matrix:     
[[  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0  11   0   0  22   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0 238   0   0   0]
 [  0   0   0   0   0   5   0   0   0]
 [  0   0   0   0   0   8   0   2   1]
 [  0   0   0   0   0   3   0   0   2]]


Classification Report:       
                             precision    recall  f1-score   support

                 Allegories       0.00      0.00      0.00         1
          Christmas Stories       0.00      0.00      0.00         2
      Detective and Mystery       1.00      0.33      0.50        33
           Ghost and Horror       0.00      0.00      0.00         2
Humorous and Wit and Satire       0.00      0.00      0.00         2
                   Literary       0.84      1.00      0.91       238
           Love and Romance       0.00      0.00      0.00         5
          Sea and Adventure       1.00  

In [84]:
param_grid1 = {'C': [0.001, 0.01, 0.1, 1, 10], 'gamma' : [1e-3, 1e-4]}
grid_search1 = GridSearchCV(svm.SVC(kernel='rbf',gamma='auto'), param_grid1)
grid_search1.fit(train,train_labels)
grid_search1.best_params_

{'C': 0.001, 'gamma': 0.001}

In [85]:
predictions=grid_search1.predict(test)
train_pred=grid_search1.predict(train)

In [86]:
print("train accuracy: {} ".format(accuracy_score(train_labels,train_pred,normalize=True, sample_weight=None)))
print("test accuracy: {} ".format(accuracy_score(test_labels,predictions,normalize=True, sample_weight=None))) 

train accuracy: 0.7971223021582734 
test accuracy: 0.7959866220735786 


In [87]:
from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix:     ")
print(confusion_matrix(test_labels, predictions))
        
print("\n\nClassification Report:       ")
print(classification_report(test_labels, predictions))

Confusion Matrix:     
[[  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0  33   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0 238   0   0   0]
 [  0   0   0   0   0   5   0   0   0]
 [  0   0   0   0   0  11   0   0   0]
 [  0   0   0   0   0   5   0   0   0]]


Classification Report:       
                             precision    recall  f1-score   support

                 Allegories       0.00      0.00      0.00         1
          Christmas Stories       0.00      0.00      0.00         2
      Detective and Mystery       0.00      0.00      0.00        33
           Ghost and Horror       0.00      0.00      0.00         2
Humorous and Wit and Satire       0.00      0.00      0.00         2
                   Literary       0.80      1.00      0.89       238
           Love and Romance       0.00      0.00      0.00         5
          Sea and Adventure       0.00  

In [88]:
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10], 'gamma' : [0.001, 0.01, 0.1, 1]}
grid_search = GridSearchCV(svm.SVC(kernel='rbf',gamma='auto'), param_grid)
grid_search.fit(train,train_labels)
grid_search.best_params_

{'C': 10, 'gamma': 0.1}

In [89]:
predictions=grid_search.predict(test)
train_pred=grid_search.predict(train)

In [90]:
print("train accuracy: {} ".format(accuracy_score(train_labels,train_pred,normalize=True, sample_weight=None)))
print("test accuracy: {} ".format(accuracy_score(test_labels,predictions,normalize=True, sample_weight=None))) 

train accuracy: 1.0 
test accuracy: 0.8394648829431438 


In [91]:
from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix:     ")
print(confusion_matrix(test_labels, predictions))
        
print("\n\nClassification Report:       ")
print(classification_report(test_labels, predictions))

Confusion Matrix:     
[[  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0  10   0   0  23   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0 238   0   0   0]
 [  0   0   0   0   0   5   0   0   0]
 [  0   0   0   0   0   8   0   2   1]
 [  0   0   0   0   0   4   0   0   1]]


Classification Report:       
                             precision    recall  f1-score   support

                 Allegories       0.00      0.00      0.00         1
          Christmas Stories       0.00      0.00      0.00         2
      Detective and Mystery       1.00      0.30      0.47        33
           Ghost and Horror       0.00      0.00      0.00         2
Humorous and Wit and Satire       0.00      0.00      0.00         2
                   Literary       0.84      1.00      0.91       238
           Love and Romance       0.00      0.00      0.00         5
          Sea and Adventure       1.00  

In [92]:
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10], 'gamma' : [0.001, 0.01, 0.1, 1, 10, 100, 1000]}
grid_search = GridSearchCV(svm.SVC(kernel='linear',gamma='auto'), param_grid)
grid_search.fit(train,train_labels)
grid_search.best_params_

{'C': 1, 'gamma': 0.001}

In [93]:
predictions=grid_search.predict(test)
train_pred=grid_search.predict(train)

In [94]:
print("train accuracy: {} ".format(accuracy_score(train_labels,train_pred,normalize=True, sample_weight=None)))
print("test accuracy: {} ".format(accuracy_score(test_labels,predictions,normalize=True, sample_weight=None))) 

train accuracy: 1.0 
test accuracy: 0.8461538461538461 


In [95]:
from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix:     ")
print(confusion_matrix(test_labels, predictions))
        
print("\n\nClassification Report:       ")
print(classification_report(test_labels, predictions))

Confusion Matrix:     
[[  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0  11   0   0  22   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0 238   0   0   0]
 [  0   0   0   0   0   5   0   0   0]
 [  0   0   0   0   0   8   0   2   1]
 [  0   0   0   0   0   3   0   0   2]]


Classification Report:       
                             precision    recall  f1-score   support

                 Allegories       0.00      0.00      0.00         1
          Christmas Stories       0.00      0.00      0.00         2
      Detective and Mystery       1.00      0.33      0.50        33
           Ghost and Horror       0.00      0.00      0.00         2
Humorous and Wit and Satire       0.00      0.00      0.00         2
                   Literary       0.84      1.00      0.91       238
           Love and Romance       0.00      0.00      0.00         5
          Sea and Adventure       1.00  

In [96]:
import sklearn
from sklearn.naive_bayes import MultinomialNB

In [97]:
mnb = MultinomialNB() 
model1 = mnb.fit(train, train_labels)
predictions = mnb.predict(test) 

In [98]:
print("train accuracy: {} ".format(mnb.fit(train, train_labels).score(train, train_labels)))
print("test accuracy: {} ".format(mnb.fit(train, train_labels).score(test, test_labels))) 

train accuracy: 0.7971223021582734 
test accuracy: 0.7959866220735786 


In [99]:
from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix:     ")
print(confusion_matrix(test_labels, predictions))
        
print("\n\nClassification Report:       ")
print(classification_report(test_labels, predictions))

Confusion Matrix:     
[[  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0  33   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0 238   0   0   0]
 [  0   0   0   0   0   5   0   0   0]
 [  0   0   0   0   0  11   0   0   0]
 [  0   0   0   0   0   5   0   0   0]]


Classification Report:       
                             precision    recall  f1-score   support

                 Allegories       0.00      0.00      0.00         1
          Christmas Stories       0.00      0.00      0.00         2
      Detective and Mystery       0.00      0.00      0.00        33
           Ghost and Horror       0.00      0.00      0.00         2
Humorous and Wit and Satire       0.00      0.00      0.00         2
                   Literary       0.80      1.00      0.89       238
           Love and Romance       0.00      0.00      0.00         5
          Sea and Adventure       0.00  

In [100]:
import sklearn
from sklearn.naive_bayes import GaussianNB

In [101]:
gnb = GaussianNB() 
model1 = gnb.fit(train, train_labels)
predictions = gnb.predict(test) 

In [102]:
print("train accuracy: {} ".format(gnb.fit(train, train_labels).score(train, train_labels)))
print("test accuracy: {} ".format(gnb.fit(train, train_labels).score(test, test_labels))) 

train accuracy: 1.0 
test accuracy: 0.8193979933110368 


In [103]:
from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix:     ")
print(confusion_matrix(test_labels, predictions))
        
print("\n\nClassification Report:       ")
print(classification_report(test_labels, predictions))

Confusion Matrix:     
[[  0   0   0   0   0   1   0   0   0]
 [  0   0   1   0   0   1   0   0   0]
 [  0   0  10   0   0  23   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   2   0   0 232   1   3   0]
 [  0   0   0   0   0   5   0   0   0]
 [  0   0   0   0   0   9   0   2   0]
 [  0   0   0   0   0   4   0   0   1]]


Classification Report:       
                             precision    recall  f1-score   support

                 Allegories       0.00      0.00      0.00         1
          Christmas Stories       0.00      0.00      0.00         2
      Detective and Mystery       0.77      0.30      0.43        33
           Ghost and Horror       0.00      0.00      0.00         2
Humorous and Wit and Satire       0.00      0.00      0.00         2
                   Literary       0.83      0.97      0.90       238
           Love and Romance       0.00      0.00      0.00         5
          Sea and Adventure       0.40  