In [ ]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix


In [ ]:
train=pd.read_csv(r"/Users/shwetabhat/Desktop/ATML/ProjectTask/DataPrepAndFeatureExt2/Train_doc2vec.csv")
test=pd.read_csv(r"/Users/shwetabhat/Desktop/ATML/ProjectTask/DataPrepAndFeatureExt2/Test_doc2vec.csv")
mergedDF=pd.concat([train,test],axis=0)

In [ ]:
del  mergedDF['Content']
del  mergedDF['id']
del  mergedDF['clean_data']
del  mergedDF['cnt']
del  mergedDF['index']

In [ ]:
mergedDF

guten_genre         0         1         2         3         4  \
0                 Literary -0.000547  0.000713 -0.001372  0.000640  0.001302   
0                 Literary  0.001031 -0.000478 -0.000320 -0.001067 -0.000375   
1                 Literary -0.000750  0.000750 -0.000054  0.000074 -0.000920   
1                 Literary  0.000172  0.000281 -0.001615  0.000227  0.001272   
2                 Literary  0.000001  0.001410  0.000221 -0.000893  0.001283   
..                     ...       ...       ...       ...       ...       ...   
690               Literary -0.001378 -0.000339 -0.000418 -0.000347 -0.000372   
691               Literary  0.001223 -0.000766 -0.000499 -0.001097  0.001223   
692               Literary -0.001595  0.000994  0.001624 -0.001042  0.001355   
693               Literary  0.001337  0.000326  0.001396 -0.000994 -0.000389   
694  Detective and Mystery  0.000704  0.001305  0.000105 -0.000335 -0.000358   

            5         6         7         8  ...  Book_Name982  Book_Name983  \
0   -0.001456  0.001515  0.000753 -0.000542  ...           0.0           0.0   
0   -0.000957  0.000200  0.000994 -0.000497  ...           0.0           0.0   
1    0.000783  0.000775 -0.000442  0.001605  ...           0.0           0.0   
1    0.001392 -0.000168  0.000849 -0.000754  ...           0.0           0.0   
2   -0.000710 -0.001542  0.000631 -0.000824  ...           0.0           0.0   
..        ...       ...       ...       ...  ...           ...           ...   
690  0.000032  0.000195  0.001527  0.001648  ...           0.0           0.0   
691  0.000951 -0.000393  0.001181 -0.000035  ...           0.0           0.0   
692  0.001465 -0.001490  0.000071 -0.000563  ...           0.0           0.0   
693  0.000446 -0.000937 -0.001496  0.001500  ...           0.0           0.0   
694  0.000479  0.000519  0.000213 -0.000555  ...           0.0           0.0   

     Book_Name984  Book_Name985  Book_Name986  Book_Name987  Book_Name988  \
0             0.0           0.0           0.0           0.0           0.0   
0             0.0           0.0           0.0           0.0           0.0   
1             0.0           0.0           0.0           0.0           0.0   
1             0.0           0.0           0.0           0.0           0.0   
2             0.0           0.0           0.0           0.0           0.0   
..            ...           ...           ...           ...           ...   
690           0.0           0.0           0.0           0.0           0.0   
691           0.0           0.0           0.0           0.0           0.0   
692           0.0           0.0           0.0           0.0           0.0   
693           0.0           0.0           0.0           0.0           0.0   
694           0.0           0.0           0.0           0.0           0.0   

     Book_Name989  Book_Name990  Book_Name991  
0             0.0           0.0           0.0  
0             0.0           0.0           0.0  
1             0.0           0.0           0.0  
1             0.0           0.0           0.0  
2             0.0           0.0           0.0  
..            ...           ...           ...  
690           0.0           0.0           0.0  
691           0.0           0.0           0.0  
692           0.0           0.0           0.0  
693           0.0           0.0           0.0  
694           0.0           0.0           0.0  

[994 rows x 1799 columns]

In [ ]:
 import pandas as pd
 import numpy as np
 from sklearn.preprocessing import OneHotEncoder
 # creating instance of one-hot-encoder
 enc = OneHotEncoder(handle_unknown='ignore')
 # passing bridge-types-cat column (label encoded values of bridge_types)
 enc_df = pd.DataFrame(enc.fit_transform(mergedDF[['Author_Name']]).toarray())
 # merge with main df bridge_df on key values
 del mergedDF['Author_Name']
 col_name=[]
 for i in range(enc_df.columns.start,enc_df.columns.stop,enc_df.columns.step):
    x="AutName"+(str(i))
    col_name.append(x)
 enc_df.columns=col_name
 mergedDF= mergedDF.join(enc_df)

In [ ]:
 enc1 = OneHotEncoder(handle_unknown='ignore')
 enc_df1 = pd.DataFrame(enc1.fit_transform(mergedDF[['Book_Name']]).toarray())
 # merge with main df bridge_df on key values
 del mergedDF['Book_Name']
 col_name=[]
 for i in range(enc_df1.columns.start,enc_df1.columns.stop,enc_df1.columns.step):
    x="Book_Name"+(str(i))
    col_name.append(x)
 enc_df1.columns=col_name
 mergedDF= mergedDF.join(enc_df1)

In [ ]:
train=mergedDF[0:695]
train_labels=train['guten_genre']
del train['guten_genre']

In [ ]:
test=mergedDF[695:]
test_labels=test['guten_genre']
del test['guten_genre']

In [ ]:
train.head()

0         1         2         3         4         5         6  \
0 -0.000547  0.000713 -0.001372  0.000640  0.001302 -0.001456  0.001515   
0  0.001031 -0.000478 -0.000320 -0.001067 -0.000375 -0.000957  0.000200   
1 -0.000750  0.000750 -0.000054  0.000074 -0.000920  0.000783  0.000775   
1  0.000172  0.000281 -0.001615  0.000227  0.001272  0.001392 -0.000168   
2  0.000001  0.001410  0.000221 -0.000893  0.001283 -0.000710 -0.001542   

          7         8         9  ...  Book_Name982  Book_Name983  \
0  0.000753 -0.000542 -0.000682  ...           0.0           0.0   
0  0.000994 -0.000497 -0.000649  ...           0.0           0.0   
1 -0.000442  0.001605  0.001222  ...           0.0           0.0   
1  0.000849 -0.000754 -0.001541  ...           0.0           0.0   
2  0.000631 -0.000824 -0.000375  ...           0.0           0.0   

   Book_Name984  Book_Name985  Book_Name986  Book_Name987  Book_Name988  \
0           0.0           0.0           0.0           0.0           0.0   
0           0.0           0.0           0.0           0.0           0.0   
1           0.0           0.0           0.0           0.0           0.0   
1           0.0           0.0           0.0           0.0           0.0   
2           0.0           0.0           0.0           0.0           0.0   

   Book_Name989  Book_Name990  Book_Name991  
0           0.0           0.0           0.0  
0           0.0           0.0           0.0  
1           0.0           0.0           0.0  
1           0.0           0.0           0.0  
2           0.0           0.0           0.0  

[5 rows x 1798 columns]

In [ ]:
test_labels.head()

396                 Literary
397                 Literary
398    Detective and Mystery
399    Detective and Mystery
400    Detective and Mystery
Name: guten_genre, dtype: object

In [ ]:
svc = svm.SVC(gamma='auto')
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}

clf = GridSearchCV(svc, parameters)

clf.fit(train,train_labels)

clf.best_params_

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


{'C': 1, 'kernel': 'rbf'}

In [ ]:
predictions=clf.predict(test)
train_pred=clf.predict(train)

print("train accuracy: {} ".format(accuracy_score(train_labels,train_pred,normalize=True, sample_weight=None)))
print("test accuracy: {} ".format(accuracy_score(test_labels,predictions,normalize=True, sample_weight=None))) 


train accuracy: 0.7985611510791367 
test accuracy: 0.7926421404682275 


In [ ]:
print("Confusion Matrix:     ")
print(confusion_matrix(test_labels, predictions))
        
print("\n\nClassification Report:       ")
print(classification_report(test_labels, predictions))

Confusion Matrix:     
[[  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0  33   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0   3   0   0   0]
 [  0   0   0   0   0 237   0   0   0]
 [  0   0   0   0   0   6   0   0   0]
 [  0   0   0   0   0  11   0   0   0]
 [  0   0   0   0   0   5   0   0   0]]


Classification Report:       
                             precision    recall  f1-score   support

                 Allegories       0.00      0.00      0.00         1
          Christmas Stories       0.00      0.00      0.00         1
      Detective and Mystery       0.00      0.00      0.00        33
           Ghost and Horror       0.00      0.00      0.00         2
Humorous and Wit and Satire       0.00      0.00      0.00         3
                   Literary       0.79      1.00      0.88       237
           Love and Romance       0.00      0.00      0.00         6
          Sea and Adventure       0.00  

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [ ]:
param_grid1 = {'C': [0.001, 0.01, 0.1, 1, 10], 'gamma' : [1e-3, 1e-4]}
grid_search1 = GridSearchCV(svm.SVC(kernel='rbf',gamma='auto'), param_grid1)
grid_search1.fit(train,train_labels)
grid_search1.best_params_

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


{'C': 0.001, 'gamma': 0.001}

In [ ]:
predictions=grid_search1.predict(test)
train_pred=grid_search1.predict(train)

In [ ]:
print("train accuracy: {} ".format(accuracy_score(train_labels,train_pred,normalize=True, sample_weight=None)))
print("test accuracy: {} ".format(accuracy_score(test_labels,predictions,normalize=True, sample_weight=None))) 

train accuracy: 0.7985611510791367 
test accuracy: 0.7926421404682275 


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix:     ")
print(confusion_matrix(test_labels, predictions))
        
print("\n\nClassification Report:       ")
print(classification_report(test_labels, predictions))

Confusion Matrix:     
[[  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0  33   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0   3   0   0   0]
 [  0   0   0   0   0 237   0   0   0]
 [  0   0   0   0   0   6   0   0   0]
 [  0   0   0   0   0  11   0   0   0]
 [  0   0   0   0   0   5   0   0   0]]


Classification Report:       
                             precision    recall  f1-score   support

                 Allegories       0.00      0.00      0.00         1
          Christmas Stories       0.00      0.00      0.00         1
      Detective and Mystery       0.00      0.00      0.00        33
           Ghost and Horror       0.00      0.00      0.00         2
Humorous and Wit and Satire       0.00      0.00      0.00         3
                   Literary       0.79      1.00      0.88       237
           Love and Romance       0.00      0.00      0.00         6
          Sea and Adventure       0.00  

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [ ]:
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10], 'gamma' : [0.001, 0.01, 0.1, 1]}
grid_search = GridSearchCV(svm.SVC(kernel='rbf',gamma='auto'), param_grid)
grid_search.fit(train,train_labels)
grid_search.best_params_

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


{'C': 10, 'gamma': 0.01}

In [ ]:
predictions=grid_search.predict(test)
train_pred=grid_search.predict(train)

In [ ]:
print("train accuracy: {} ".format(accuracy_score(train_labels,train_pred,normalize=True, sample_weight=None)))
print("test accuracy: {} ".format(accuracy_score(test_labels,predictions,normalize=True, sample_weight=None))) 

train accuracy: 0.8158273381294964 
test accuracy: 0.7959866220735786 


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix:     ")
print(confusion_matrix(test_labels, predictions))
        
print("\n\nClassification Report:       ")
print(classification_report(test_labels, predictions))

Confusion Matrix:     
[[  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   1   0   0   0]
 [  0   0   1   0   0  32   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0   3   0   0   0]
 [  0   0   0   0   0 237   0   0   0]
 [  0   0   0   0   0   6   0   0   0]
 [  0   0   0   0   0  11   0   0   0]
 [  0   0   0   0   0   5   0   0   0]]


Classification Report:       
                             precision    recall  f1-score   support

                 Allegories       0.00      0.00      0.00         1
          Christmas Stories       0.00      0.00      0.00         1
      Detective and Mystery       1.00      0.03      0.06        33
           Ghost and Horror       0.00      0.00      0.00         2
Humorous and Wit and Satire       0.00      0.00      0.00         3
                   Literary       0.80      1.00      0.89       237
           Love and Romance       0.00      0.00      0.00         6
          Sea and Adventure       0.00  

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [ ]:
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10], 'gamma' : [0.001, 0.01, 0.1, 1, 10, 100, 1000]}
grid_search = GridSearchCV(svm.SVC(kernel='linear',gamma='auto'), param_grid)
grid_search.fit(train,train_labels)
grid_search.best_params_

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


{'C': 0.001, 'gamma': 0.001}

In [ ]:
predictions=clf.predict(test)
train_pred=clf.predict(train)

In [ ]:
print("train accuracy: {} ".format(accuracy_score(train_labels,train_pred,normalize=True, sample_weight=None)))
print("test accuracy: {} ".format(accuracy_score(test_labels,predictions,normalize=True, sample_weight=None))) 

train accuracy: 0.7985611510791367 
test accuracy: 0.7926421404682275 


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix:     ")
print(confusion_matrix(test_labels, predictions))
        
print("\n\nClassification Report:       ")
print(classification_report(test_labels, predictions))

Confusion Matrix:     
[[  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0  33   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0   3   0   0   0]
 [  0   0   0   0   0 237   0   0   0]
 [  0   0   0   0   0   6   0   0   0]
 [  0   0   0   0   0  11   0   0   0]
 [  0   0   0   0   0   5   0   0   0]]


Classification Report:       
                             precision    recall  f1-score   support

                 Allegories       0.00      0.00      0.00         1
          Christmas Stories       0.00      0.00      0.00         1
      Detective and Mystery       0.00      0.00      0.00        33
           Ghost and Horror       0.00      0.00      0.00         2
Humorous and Wit and Satire       0.00      0.00      0.00         3
                   Literary       0.79      1.00      0.88       237
           Love and Romance       0.00      0.00      0.00         6
          Sea and Adventure       0.00  

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
