In [37]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [38]:
mergedDF=pd.read_csv(r"/Users/shwetabhat/Desktop/ATML/ProjectTask/DataPrepAndFeatureExt2/books_ALLFeatures.csv")

In [45]:
mergedDF.head()

file  male_count  female_count  para_count  \
0                   pg15895.txt   -0.107486     -0.109654   -0.160190   
1                   pg33945.txt   -0.001378     -0.023623   -0.020020   
2                    pg1392.txt   -0.127530     -0.164698   -0.228365   
3  pg19337DickensChristCarl.txt   -0.078988     -0.155239   -0.149864   
4                   pg43190.txt    0.110572      0.174208    0.138396   

                                             Content        guten_genre  \
0  In the steeple of an old church was a beautifu...         Allegories   
1  A solitary fisher ploughed the lively blue of ...         Allegories   
2  Strictly speaking, there were only six Poor Tr...  Christmas Stories   
3  The combined qualities of the realist and the ...  Christmas Stories   
4  page 01b In the heart of a very maze of courts...  Christmas Stories   

       Puch                       book_id  Conj-Prep  \
0  0.000283                   pg15895.txt   0.100930   
1  0.000769                   pg33945.txt   0.098077   
2  0.000114                    pg1392.txt   0.109298   
3  0.000422  pg19337DickensChristCarl.txt   0.097503   
4  0.002142                   pg43190.txt   0.100023   

                                          clean_data  ...  Book_Name981  \
0   steeple church beautiful chime bell many year...  ...           0.0   
1   solitary fisher ploughed lively blue southern...  ...           0.0   
2   strictly speaking poor traveller traveller th...  ...           0.0   
3   combined quality realist idealist dickens pos...  ...           0.0   
4   page heart maze court lane proclaims multitud...  ...           0.0   

   Book_Name982  Book_Name983  Book_Name984  Book_Name985  Book_Name986  \
0           0.0           0.0           0.0           0.0           0.0   
1           0.0           0.0           0.0           0.0           0.0   
2           0.0           0.0           0.0           0.0           0.0   
3           0.0           0.0           0.0           0.0           0.0   
4           0.0           0.0           0.0           0.0           0.0   

   Book_Name987  Book_Name988  Book_Name989  Book_Name990  
0           0.0           0.0           0.0           0.0  
1           0.0           0.0           0.0           0.0  
2           0.0           0.0           0.0           0.0  
3           0.0           0.0           0.0           0.0  
4           0.0           0.0           0.0           0.0  

[5 rows x 1520 columns]

In [49]:
mergedDF.head()

male_count  female_count  para_count        guten_genre      Puch  \
0   -0.107486     -0.109654   -0.160190         Allegories  0.000283   
1   -0.001378     -0.023623   -0.020020         Allegories  0.000769   
2   -0.127530     -0.164698   -0.228365  Christmas Stories  0.000114   
3   -0.078988     -0.155239   -0.149864  Christmas Stories  0.000422   
4    0.110572      0.174208    0.138396  Christmas Stories  0.002142   

   Conj-Prep  no_ofCommas   no_coln  no_period  no_doubleQuotes  ...  \
0   0.100930     0.000341  0.000549   0.000282         0.000088  ...   
1   0.098077     0.000840  0.002242   0.000816         0.001598  ...   
2   0.109298     0.000161  0.000065   0.000092         0.000041  ...   
3   0.097503     0.000466  0.000558   0.000349         0.000293  ...   
4   0.100023     0.001976  0.001293   0.001873         0.006477  ...   

   Book_Name981  Book_Name982  Book_Name983  Book_Name984  Book_Name985  \
0           0.0           0.0           0.0           0.0           0.0   
1           0.0           0.0           0.0           0.0           0.0   
2           0.0           0.0           0.0           0.0           0.0   
3           0.0           0.0           0.0           0.0           0.0   
4           0.0           0.0           0.0           0.0           0.0   

   Book_Name986  Book_Name987  Book_Name988  Book_Name989  Book_Name990  
0           0.0           0.0           0.0           0.0           0.0  
1           0.0           0.0           0.0           0.0           0.0  
2           0.0           0.0           0.0           0.0           0.0  
3           0.0           0.0           0.0           0.0           0.0  
4           0.0           0.0           0.0           0.0           0.0  

[5 rows x 1514 columns]

In [ ]:
 # creating instance of one-hot-encoder
 enc = OneHotEncoder(handle_unknown='ignore')
 # passing bridge-types-cat column (label encoded values of bridge_types)
 enc_df = pd.DataFrame(enc.fit_transform(mergedDF[['Author_Name']]).toarray())
 # merge with main df bridge_df on key values
 del mergedDF['Author_Name']
 col_name=[]
 for i in range(enc_df.columns.start,enc_df.columns.stop,enc_df.columns.step):
    x="AutName"+(str(i))
    col_name.append(x)
 enc_df.columns=col_name
 mergedDF= mergedDF.join(enc_df)

In [48]:
del mergedDF['file']
del mergedDF['Content']
del mergedDF['clean_data']
del mergedDF['book_id']

del mergedDF['lexical_diversity_score_onChunk']
del mergedDF['flesh_reading_score']


In [ ]:
 enc1 = OneHotEncoder(handle_unknown='ignore')
 enc_df1 = pd.DataFrame(enc1.fit_transform(mergedDF[['Book_Name']]).toarray())
 # merge with main df bridge_df on key values
 del mergedDF['Book_Name']
 col_name=[]
 for i in range(enc_df1.columns.start,enc_df1.columns.stop,enc_df1.columns.step):
    x="Book_Name"+(str(i))
    col_name.append(x)
 enc_df1.columns=col_name
 mergedDF= mergedDF.join(enc_df1)

In [50]:
y=mergedDF['guten_genre']
del  mergedDF['guten_genre']
y.head()

0           Allegories
1           Allegories
2    Christmas Stories
3    Christmas Stories
4    Christmas Stories
Name: guten_genre, dtype: object

In [51]:
X=mergedDF

In [52]:
y.shape

(993,)

In [53]:
 train, test, train_labels, test_labels = train_test_split(X, y, test_size=0.3, random_state=42,stratify=y)

In [55]:
train.head()

male_count  female_count  para_count      Puch  Conj-Prep  no_ofCommas  \
393    0.259142      0.031339    0.163573  0.002088   0.096182     0.002001   
433    0.011874      0.029219   -0.084376  0.000954   0.086878     0.000795   
579   -0.031396     -0.034469   -0.093853  0.000609   0.098459     0.000756   
72    -0.022419     -0.106719   -0.030628  0.000783   0.103279     0.000560   
71     0.007979      0.029545    0.044478  0.000978   0.095528     0.000971   

      no_coln  no_period  no_doubleQuotes  number_sen  ...  Book_Name981  \
393  0.001600   0.001547         0.007481    0.001639  ...           0.0   
433  0.000809   0.001202         0.000955    0.001150  ...           0.0   
579  0.002493   0.000416         0.000199    0.000499  ...           0.0   
72   0.000279   0.000707         0.001082    0.000795  ...           0.0   
71   0.001423   0.000959         0.000955    0.000982  ...           0.0   

     Book_Name982  Book_Name983  Book_Name984  Book_Name985  Book_Name986  \
393           0.0           0.0           0.0           0.0           0.0   
433           0.0           0.0           0.0           0.0           0.0   
579           0.0           0.0           0.0           0.0           0.0   
72            0.0           0.0           0.0           0.0           0.0   
71            0.0           0.0           0.0           0.0           0.0   

     Book_Name987  Book_Name988  Book_Name989  Book_Name990  
393           0.0           0.0           0.0           0.0  
433           0.0           0.0           0.0           0.0  
579           0.0           0.0           0.0           0.0  
72            0.0           0.0           0.0           0.0  
71            0.0           0.0           0.0           0.0  

[5 rows x 1513 columns]

In [56]:
svc = svm.SVC(gamma='auto')
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}

In [57]:
clf = GridSearchCV(svc, parameters)

In [58]:
clf.fit(train,train_labels)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [1, 10], 'kernel': ('linear', 'rbf')},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [59]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [60]:
predictions=clf.predict(test)
train_pred=clf.predict(train)

In [61]:
print("train accuracy: {} ".format(accuracy_score(train_labels,train_pred,normalize=True, sample_weight=None)))
print("test accuracy: {} ".format(accuracy_score(test_labels,predictions,normalize=True, sample_weight=None))) 

train accuracy: 1.0 
test accuracy: 0.8456375838926175 


In [62]:
from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix:     ")
print(confusion_matrix(test_labels, predictions))
        
print("\n\nClassification Report:       ")
print(classification_report(test_labels, predictions))

Confusion Matrix:     
[[  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   1   0   0   0]
 [  0   0  15   0   0  18   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   4   0   0 232   0   2   0]
 [  0   0   0   0   0   5   0   0   0]
 [  0   0   0   0   0   7   0   4   0]
 [  0   0   0   0   0   1   0   3   1]]


Classification Report:       
                             precision    recall  f1-score   support

                 Allegories       0.00      0.00      0.00         1
          Christmas Stories       0.00      0.00      0.00         1
      Detective and Mystery       0.79      0.45      0.58        33
           Ghost and Horror       0.00      0.00      0.00         2
Humorous and Wit and Satire       0.00      0.00      0.00         2
                   Literary       0.86      0.97      0.92       238
           Love and Romance       0.00      0.00      0.00         5
          Sea and Adventure       0.44  

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [63]:
param_grid1 = {'C': [0.001, 0.01, 0.1, 1, 10], 'gamma' : [1e-3, 1e-4]}
grid_search1 = GridSearchCV(svm.SVC(kernel='rbf',gamma='auto'), param_grid1)
grid_search1.fit(train,train_labels)
grid_search1.best_params_

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


{'C': 0.001, 'gamma': 0.001}

In [64]:
predictions=grid_search1.predict(test)
train_pred=grid_search1.predict(train)

In [65]:
print("train accuracy: {} ".format(accuracy_score(train_labels,train_pred,normalize=True, sample_weight=None)))
print("test accuracy: {} ".format(accuracy_score(test_labels,predictions,normalize=True, sample_weight=None))) 

train accuracy: 0.7971223021582734 
test accuracy: 0.7986577181208053 


In [66]:
from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix:     ")
print(confusion_matrix(test_labels, predictions))
        
print("\n\nClassification Report:       ")
print(classification_report(test_labels, predictions))

Confusion Matrix:     
[[  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0  33   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0 238   0   0   0]
 [  0   0   0   0   0   5   0   0   0]
 [  0   0   0   0   0  11   0   0   0]
 [  0   0   0   0   0   5   0   0   0]]


Classification Report:       
                             precision    recall  f1-score   support

                 Allegories       0.00      0.00      0.00         1
          Christmas Stories       0.00      0.00      0.00         1
      Detective and Mystery       0.00      0.00      0.00        33
           Ghost and Horror       0.00      0.00      0.00         2
Humorous and Wit and Satire       0.00      0.00      0.00         2
                   Literary       0.80      1.00      0.89       238
           Love and Romance       0.00      0.00      0.00         5
          Sea and Adventure       0.00  

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [67]:
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10], 'gamma' : [0.001, 0.01, 0.1, 1]}
grid_search = GridSearchCV(svm.SVC(kernel='rbf',gamma='auto'), param_grid)
grid_search.fit(train,train_labels)
grid_search.best_params_

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


{'C': 10, 'gamma': 0.1}

In [68]:
predictions=grid_search.predict(test)
train_pred=grid_search.predict(train)

In [69]:
print("train accuracy: {} ".format(accuracy_score(train_labels,train_pred,normalize=True, sample_weight=None)))
print("test accuracy: {} ".format(accuracy_score(test_labels,predictions,normalize=True, sample_weight=None))) 

train accuracy: 1.0 
test accuracy: 0.8389261744966443 


In [70]:
from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix:     ")
print(confusion_matrix(test_labels, predictions))
        
print("\n\nClassification Report:       ")
print(classification_report(test_labels, predictions))

Confusion Matrix:     
[[  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   1   0   0   0]
 [  0   0  15   0   0  18   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   2   0   0 234   0   2   0]
 [  0   0   0   0   0   5   0   0   0]
 [  0   0   0   0   0  10   0   1   0]
 [  0   0   0   0   0   2   0   3   0]]


Classification Report:       
                             precision    recall  f1-score   support

                 Allegories       0.00      0.00      0.00         1
          Christmas Stories       0.00      0.00      0.00         1
      Detective and Mystery       0.88      0.45      0.60        33
           Ghost and Horror       0.00      0.00      0.00         2
Humorous and Wit and Satire       0.00      0.00      0.00         2
                   Literary       0.85      0.98      0.91       238
           Love and Romance       0.00      0.00      0.00         5
          Sea and Adventure       0.17  

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Both Linear and RBF kernel shows the same performance so using linear kernel.

In [71]:
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10], 'gamma' : [0.001, 0.01, 0.1, 1, 10, 100, 1000]}
grid_search = GridSearchCV(svm.SVC(kernel='linear',gamma='auto'), param_grid)
grid_search.fit(train,train_labels)
grid_search.best_params_

/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


{'C': 1, 'gamma': 0.001}

In [72]:
predictions=clf.predict(test)
train_pred=clf.predict(train)

In [73]:
print("train accuracy: {} ".format(accuracy_score(train_labels,train_pred,normalize=True, sample_weight=None)))
print("test accuracy: {} ".format(accuracy_score(test_labels,predictions,normalize=True, sample_weight=None))) 

train accuracy: 1.0 
test accuracy: 0.8456375838926175 


In [74]:
from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix:     ")
print(confusion_matrix(test_labels, predictions))
        
print("\n\nClassification Report:       ")
print(classification_report(test_labels, predictions))

Confusion Matrix:     
[[  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   1   0   0   0]
 [  0   0  15   0   0  18   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   4   0   0 232   0   2   0]
 [  0   0   0   0   0   5   0   0   0]
 [  0   0   0   0   0   7   0   4   0]
 [  0   0   0   0   0   1   0   3   1]]


Classification Report:       
                             precision    recall  f1-score   support

                 Allegories       0.00      0.00      0.00         1
          Christmas Stories       0.00      0.00      0.00         1
      Detective and Mystery       0.79      0.45      0.58        33
           Ghost and Horror       0.00      0.00      0.00         2
Humorous and Wit and Satire       0.00      0.00      0.00         2
                   Literary       0.86      0.97      0.92       238
           Love and Romance       0.00      0.00      0.00         5
          Sea and Adventure       0.44  

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
