In [213]:
import pandas as pd
import numpy as np
import math

import sklearn
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [378]:
mergedDF.to_csv("/Users/shwetabhat/Desktop/ATML/ProjectTask/DataPrepAndFeatureExt2/dataWithBookStatsWithTTR_unNormal.csv",header=True,index=False)

In [379]:
mergedDF.head()

book_id  flesh_reading_score                                     Book_Name  \
0  pg42534                76.21                              The Narrow House   
1  pg33468                56.60               Roland Cashel- Volume I (of II)   
2  pg12733                58.39  Tokyo to Tijuana: Gabriele Departing America   
3  pg16968                78.78                          The Bad Man: A Novel   
4  pg28509                62.63                           The Brass Bound Box   

  guten_genre                                    Author_Name  Puch  Conj-Prep  \
0    Literary                                  Scott| Evelyn    81         96   
1    Literary                           Lever| Charles James    40         98   
2    Literary                     Sills| Steven David Justin    51        118   
3    Literary  Browne| Porter Emerson| Towne| Charles Hanson    89         70   
4    Literary                                Raymond| Evelyn    51         89   

   no_ofCommas  no_coln  no_period  no_doubleQuotes  book_lenght  book_sen  \
0         2483        5       4954             1021       288192      5094   
1        13761       82       5682             2354       735047      6452   
2         6362      258       9630             2136      1023437     10479   
3         3673       92       4501             1930       284238      6177   
4         5409      264       3281             3641       390590      4369   

   number_sen  lexical_diversity_score_onChunk  
0        1076                               24  
1        1363                               30  
2        2213                               34  
3        1305                               22  
4         923                               28

In [380]:
del  mergedDF['book_id']

In [381]:
 # creating instance of one-hot-encoder
 enc = OneHotEncoder(handle_unknown='ignore')
 # passing bridge-types-cat column (label encoded values of bridge_types)
 enc_df = pd.DataFrame(enc.fit_transform(mergedDF[['Author_Name']]).toarray())
 # merge with main df bridge_df on key values
 del mergedDF['Author_Name']
 col_name=[]
 for i in range(enc_df.columns.start,enc_df.columns.stop,enc_df.columns.step):
    x="AutName"+(str(i))
    col_name.append(x)
 enc_df.columns=col_name
 mergedDF= mergedDF.join(enc_df)

In [382]:
 enc1 = OneHotEncoder(handle_unknown='ignore')
 enc_df1 = pd.DataFrame(enc1.fit_transform(mergedDF[['Book_Name']]).toarray())
 # merge with main df bridge_df on key values
 del mergedDF['Book_Name']
 col_name=[]
 for i in range(enc_df1.columns.start,enc_df1.columns.stop,enc_df1.columns.step):
    x="Book_Name"+(str(i))
    col_name.append(x)
 enc_df1.columns=col_name
 mergedDF= mergedDF.join(enc_df1)

In [383]:
mergedDF.head()

flesh_reading_score guten_genre  Puch  Conj-Prep  no_ofCommas  no_coln  \
0                76.21    Literary    81         96         2483        5   
1                56.60    Literary    40         98        13761       82   
2                58.39    Literary    51        118         6362      258   
3                78.78    Literary    89         70         3673       92   
4                62.63    Literary    51         89         5409      264   

   no_period  no_doubleQuotes  book_lenght  book_sen  ...  Book_Name982  \
0       4954             1021       288192      5094  ...           0.0   
1       5682             2354       735047      6452  ...           0.0   
2       9630             2136      1023437     10479  ...           0.0   
3       4501             1930       284238      6177  ...           0.0   
4       3281             3641       390590      4369  ...           0.0   

   Book_Name983  Book_Name984  Book_Name985  Book_Name986  Book_Name987  \
0           0.0           0.0           0.0           0.0           0.0   
1           0.0           0.0           0.0           0.0           0.0   
2           0.0           0.0           0.0           0.0           0.0   
3           0.0           0.0           0.0           0.0           0.0   
4           0.0           0.0           0.0           0.0           0.0   

   Book_Name988  Book_Name989  Book_Name990  Book_Name991  
0           0.0           0.0           0.0           0.0  
1           0.0           0.0           0.0           0.0  
2           0.0           0.0           0.0           0.0  
3           0.0           0.0           0.0           0.0  
4           0.0           0.0           0.0           0.0  

[5 rows x 1510 columns]

In [384]:
mergedDF.columns[1:20]

Index(['guten_genre', 'Puch', 'Conj-Prep', 'no_ofCommas', 'no_coln',
       'no_period', 'no_doubleQuotes', 'book_lenght', 'book_sen', 'number_sen',
       'lexical_diversity_score_onChunk', 'AutName0', 'AutName1', 'AutName2',
       'AutName3', 'AutName4', 'AutName5', 'AutName6', 'AutName7'],
      dtype='object')

In [385]:
y=mergedDF['guten_genre']
del  mergedDF['guten_genre']
y.head()

0    Literary
1    Literary
2    Literary
3    Literary
4    Literary
Name: guten_genre, dtype: object

In [182]:
X.columns[1:20]
#list(X[ 'female_count', 'para_count'])
#, 'no_ofCommas', 'no_coln', 'no_period', 'no_doubleQuotes','number_sen','Compound', 'Neg', 'Neutral', 'Positive']]

Index(['Conj-Prep', 'no_ofCommas', 'no_coln', 'no_period', 'no_doubleQuotes',
       'number_sen', 'PropNouns', 'Neg', 'Neutral', 'Positive', 'AutName0',
       'AutName1', 'AutName2', 'AutName3', 'AutName4', 'AutName5', 'AutName6',
       'AutName7', 'AutName8'],
      dtype='object')

In [386]:
X=mergedDF

In [387]:
 train, test, train_labels, test_labels = train_test_split(X, y, test_size=0.3, random_state=42,stratify=y)

In [393]:
gnb = MultinomialNB() 
model1 = gnb.fit(train, train_labels)
predictions = gnb.predict(test) 

In [394]:
list(predictions)

['Literary',
 'Literary',
 'Literary',
 'Literary',
 'Detective and Mystery',
 'Sea and Adventure',
 'Detective and Mystery',
 'Sea and Adventure',
 'Detective and Mystery',
 'Western Stories',
 'Humorous and Wit and Satire',
 'Sea and Adventure',
 'Sea and Adventure',
 'Literary',
 'Western Stories',
 'Literary',
 'Detective and Mystery',
 'Detective and Mystery',
 'Literary',
 'Western Stories',
 'Sea and Adventure',
 'Sea and Adventure',
 'Sea and Adventure',
 'Western Stories',
 'Sea and Adventure',
 'Western Stories',
 'Literary',
 'Sea and Adventure',
 'Sea and Adventure',
 'Western Stories',
 'Love and Romance',
 'Literary',
 'Detective and Mystery',
 'Sea and Adventure',
 'Detective and Mystery',
 'Sea and Adventure',
 'Literary',
 'Ghost and Horror',
 'Detective and Mystery',
 'Western Stories',
 'Literary',
 'Western Stories',
 'Western Stories',
 'Western Stories',
 'Western Stories',
 'Literary',
 'Western Stories',
 'Detective and Mystery',
 'Christmas Stories',
 'Detectiv

In [395]:
print("train accuracy: {} ".format(gnb.fit(train, train_labels).score(train, train_labels)))
print("test accuracy: {} ".format(gnb.fit(train, train_labels).score(test, test_labels))) 

train accuracy: 0.23453237410071942 
test accuracy: 0.18729096989966554 


In [396]:
from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix:     ")
print(confusion_matrix(test_labels, predictions))
        
print("\n\nClassification Report:       ")
print(classification_report(test_labels, predictions))

Confusion Matrix:     
[[ 0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  1  0  1]
 [ 0  1 13  1  2  5  5  3  3]
 [ 0  0  0  1  0  1  0  0  0]
 [ 0  0  0  0  0  1  1  0  0]
 [ 0  3 45  9 10 35  4 84 48]
 [ 0  0  2  0  0  1  0  2  0]
 [ 0  0  3  0  0  1  0  6  1]
 [ 0  0  0  0  1  2  0  1  1]]


Classification Report:       
                             precision    recall  f1-score   support

                 Allegories       0.00      0.00      0.00         1
          Christmas Stories       0.00      0.00      0.00         2
      Detective and Mystery       0.21      0.39      0.27        33
           Ghost and Horror       0.09      0.50      0.15         2
Humorous and Wit and Satire       0.00      0.00      0.00         2
                   Literary       0.76      0.15      0.25       238
           Love and Romance       0.00      0.00      0.00         5
          Sea and Adventure       0.06      0.55      0.11        11
            Western Stories       0.02      0.20    

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [397]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB() 
model1 = gnb.fit(train, train_labels)
predictions = gnb.predict(test) 

In [398]:
list(predictions)

['Literary',
 'Detective and Mystery',
 'Literary',
 'Detective and Mystery',
 'Detective and Mystery',
 'Detective and Mystery',
 'Literary',
 'Literary',
 'Detective and Mystery',
 'Literary',
 'Literary',
 'Literary',
 'Literary',
 'Literary',
 'Detective and Mystery',
 'Literary',
 'Detective and Mystery',
 'Detective and Mystery',
 'Literary',
 'Humorous and Wit and Satire',
 'Literary',
 'Literary',
 'Literary',
 'Christmas Stories',
 'Detective and Mystery',
 'Detective and Mystery',
 'Detective and Mystery',
 'Literary',
 'Ghost and Horror',
 'Western Stories',
 'Detective and Mystery',
 'Literary',
 'Detective and Mystery',
 'Literary',
 'Detective and Mystery',
 'Christmas Stories',
 'Literary',
 'Christmas Stories',
 'Literary',
 'Literary',
 'Detective and Mystery',
 'Detective and Mystery',
 'Literary',
 'Detective and Mystery',
 'Literary',
 'Detective and Mystery',
 'Literary',
 'Literary',
 'Christmas Stories',
 'Literary',
 'Detective and Mystery',
 'Literary',
 'Liter

In [399]:
print("train accuracy: {} ".format(gnb.fit(train, train_labels).score(train, train_labels)))
print("test accuracy: {} ".format(gnb.fit(train, train_labels).score(test, test_labels))) 

train accuracy: 0.437410071942446 
test accuracy: 0.5150501672240803 


In [400]:
from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix:     ")
print(confusion_matrix(test_labels, predictions))
        
print("\n\nClassification Report:       ")
print(classification_report(test_labels, predictions))

Confusion Matrix:     
[[  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   5  18   0   1   6   0   0   3]
 [  0   1   0   1   0   0   0   0   0]
 [  0   0   2   0   0   0   0   0   0]
 [  0  22  63  12   2 133   0   1   5]
 [  0   0   1   1   0   3   0   0   0]
 [  0   1   2   1   0   5   0   2   0]
 [  0   1   2   0   0   2   0   0   0]]


Classification Report:       
                             precision    recall  f1-score   support

                 Allegories       0.00      0.00      0.00         1
          Christmas Stories       0.00      0.00      0.00         2
      Detective and Mystery       0.20      0.55      0.30        33
           Ghost and Horror       0.07      0.50      0.12         2
Humorous and Wit and Satire       0.00      0.00      0.00         2
                   Literary       0.88      0.56      0.68       238
           Love and Romance       0.00      0.00      0.00         5
          Sea and Adventure       0.67  

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
