In [12]:
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer 

In [2]:
data = pd.read_csv(r"/Users/surabhi/Desktop/ATML_Project/InitialDataPrep-FeatureExtractionPhase-May-2020/DataPreprocessed/books_ALLFeatures.csv")

In [5]:
data.head(3)

Unnamed: 0         file  male_count  female_count  para_count  \
0           0  pg15895.txt   -0.107486     -0.109654   -0.160190   
1           1  pg33945.txt   -0.001378     -0.023623   -0.020020   
2           2   pg1392.txt   -0.127530     -0.164698   -0.228365   

                                             Content  \
0  In the steeple of an old church was a beautifu...   
1  A solitary fisher ploughed the lively blue of ...   
2  Strictly speaking, there were only six Poor Tr...   

                   Book_Name        guten_genre        Author_Name      Puch  \
0         Allegories of Life         Allegories  Adams| Mrs. J. S.  0.000283   
1            The Unknown Sea         Allegories  Housman| Clemence  0.000769   
2  The Seven Poor Travellers  Christmas Stories   Dickens| Charles  0.000114   

   ... no_doubleQuotes  number_sen normalized_ttr_chunk  flesh_reading_score  \
0  ...        0.000088    0.000287            -0.078984                65.72   
1  ...        0.001598    0.000882             0.039468                68.57   
2  ...        0.000041    0.000095             0.120310                57.19   

   normalized_frs  PropNouns  Compound       Neg   Neutral  Positive  
0        0.018357        0.0  0.149781  0.069946  0.814285  0.115770  
1        0.055665        0.0  0.131898  0.058432  0.838624  0.102951  
2       -0.093307        0.0  0.037147  0.077263  0.823015  0.099725  

[3 rows x 26 columns]

In [10]:
del data['flesh_reading_score']

In [13]:
enc1 = OneHotEncoder(handle_unknown='ignore')
enc_df1 = pd.DataFrame(enc1.fit_transform(data[['Book_Name']]).toarray())
 # merge with main df bridge_df on key values
del data['Book_Name']
col_name=[]
for i in range(enc_df1.columns.start,enc_df1.columns.stop,enc_df1.columns.step):
    x="Book_Name"+(str(i))
    col_name.append(x)
enc_df1.columns=col_name
data = data.join(enc_df1)

In [14]:
enc1 = OneHotEncoder(handle_unknown='ignore')
enc_df1 = pd.DataFrame(enc1.fit_transform(data[['Author_Name']]).toarray())
 # merge with main df bridge_df on key values
del data['Author_Name']
col_name=[]
for i in range(enc_df1.columns.start,enc_df1.columns.stop,enc_df1.columns.step):
    x="Author_Name"+(str(i))
    col_name.append(x)
enc_df1.columns=col_name
data = data.join(enc_df1)

In [15]:
data.head(3)

Unnamed: 0         file  male_count  female_count  para_count  \
0           0  pg15895.txt   -0.107486     -0.109654   -0.160190   
1           1  pg33945.txt   -0.001378     -0.023623   -0.020020   
2           2   pg1392.txt   -0.127530     -0.164698   -0.228365   

                                             Content        guten_genre  \
0  In the steeple of an old church was a beautifu...         Allegories   
1  A solitary fisher ploughed the lively blue of ...         Allegories   
2  Strictly speaking, there were only six Poor Tr...  Christmas Stories   

       Puch      book_id  Conj-Prep  ... Author_Name495  Author_Name496  \
0  0.000283  pg15895.txt   0.100930  ...            0.0             0.0   
1  0.000769  pg33945.txt   0.098077  ...            0.0             0.0   
2  0.000114   pg1392.txt   0.109298  ...            0.0             0.0   

   Author_Name497  Author_Name498  Author_Name499  Author_Name500  \
0             0.0             0.0             0.0             0.0   
1             0.0             0.0             0.0             0.0   
2             0.0             0.0             0.0             0.0   

   Author_Name501  Author_Name502  Author_Name503  Author_Name504  
0             0.0             0.0             0.0             0.0  
1             0.0             0.0             0.0             0.0  
2             0.0             0.0             0.0             0.0  

[3 rows x 1519 columns]

In [16]:
alldata_train, alldata_test = train_test_split(data, test_size=0.3, random_state=42, stratify = np.array(data['guten_genre']))

In [17]:
len(alldata_train)

695

In [18]:
y_train = alldata_train['guten_genre']

In [19]:
y_test = alldata_test['guten_genre']

In [20]:
del alldata_train['guten_genre']
del alldata_test['guten_genre']

In [21]:
del alldata_train['book_id']
del alldata_train['file']

In [22]:
del alldata_train['clean_data']

In [26]:
del alldata_train['Content']

In [27]:
alldata_train.head()

Unnamed: 0  male_count  female_count  para_count      Puch  Conj-Prep  \
393         393    0.259142      0.031339    0.163573  0.002088   0.096182   
433         433    0.011874      0.029219   -0.084376  0.000954   0.086878   
579         579   -0.031396     -0.034469   -0.093853  0.000609   0.098459   
72           72   -0.022419     -0.106719   -0.030628  0.000783   0.103279   
71           71    0.007979      0.029545    0.044478  0.000978   0.095528   

     no_ofCommas   no_coln  no_period  no_doubleQuotes  ...  Author_Name495  \
393     0.002001  0.001600   0.001547         0.007481  ...             0.0   
433     0.000795  0.000809   0.001202         0.000955  ...             0.0   
579     0.000756  0.002493   0.000416         0.000199  ...             0.0   
72      0.000560  0.000279   0.000707         0.001082  ...             0.0   
71      0.000971  0.001423   0.000959         0.000955  ...             0.0   

     Author_Name496  Author_Name497  Author_Name498  Author_Name499  \
393             0.0             0.0             0.0             0.0   
433             0.0             0.0             0.0             0.0   
579             0.0             0.0             0.0             0.0   
72              0.0             0.0             0.0             0.0   
71              0.0             0.0             0.0             0.0   

     Author_Name500  Author_Name501  Author_Name502  Author_Name503  \
393             0.0             0.0             0.0             0.0   
433             0.0             0.0             0.0             0.0   
579             0.0             0.0             0.0             0.0   
72              0.0             0.0             0.0             0.0   
71              0.0             0.0             0.0             0.0   

     Author_Name504  
393             0.0  
433             0.0  
579             0.0  
72              0.0  
71              0.0  

[5 rows x 1514 columns]

In [28]:
del alldata_test['book_id']
del alldata_test['file']
del alldata_test['clean_data']

In [30]:
del alldata_test['Content']

In [31]:
alldata_test.head()

Unnamed: 0  male_count  female_count  para_count      Puch  Conj-Prep  \
770         770   -0.029639      0.142486    0.110956  0.000923   0.084898   
617         617   -0.087395      0.012828   -0.050855  0.000806   0.083267   
381         381    0.013916      0.351815    0.116048  0.001479   0.091347   
685         685   -0.075141     -0.061950   -0.146611  0.000480   0.106100   
81           81   -0.035433     -0.097096   -0.099087  0.000643   0.095591   

     no_ofCommas   no_coln  no_period  no_doubleQuotes  ...  Author_Name495  \
770     0.000953  0.001256   0.001022         0.000439  ...             0.0   
617     0.000636  0.000735   0.000801         0.001277  ...             0.0   
381     0.001324  0.002493   0.001539         0.001070  ...             0.0   
685     0.000670  0.000614   0.000358         0.000333  ...             0.0   
81      0.000651  0.000781   0.000670         0.000411  ...             0.0   

     Author_Name496  Author_Name497  Author_Name498  Author_Name499  \
770             0.0             0.0             0.0             0.0   
617             0.0             0.0             0.0             0.0   
381             0.0             0.0             0.0             0.0   
685             0.0             0.0             0.0             0.0   
81              0.0             0.0             0.0             0.0   

     Author_Name500  Author_Name501  Author_Name502  Author_Name503  \
770             0.0             0.0             0.0             0.0   
617             0.0             0.0             0.0             0.0   
381             0.0             0.0             0.0             0.0   
685             0.0             0.0             0.0             0.0   
81              0.0             0.0             0.0             0.0   

     Author_Name504  
770             0.0  
617             0.0  
381             0.0  
685             0.0  
81              0.0  

[5 rows x 1514 columns]

In [46]:
logreg = LogisticRegression(solver = 'lbfgs',penalty = 'l2', multi_class = 'multinomial')
logreg.fit(alldata_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [47]:
y_pred = logreg.predict(alldata_test)

In [48]:
count_misclassified = (y_test != y_pred).sum()

In [52]:
from sklearn.metrics import accuracy_score, f1_score
from sklearn.metrics import classification_report, confusion_matrix

print('Testing accuracy %s' % accuracy_score(y_test, y_pred))
print('Testing F1 score: {}'.format(f1_score(y_test, y_pred, average='weighted')))

Testing accuracy 0.8993288590604027
Testing F1 score: 0.8565077726151551


In [55]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[  0   0   1   0   0   0   0   0   0]
 [  0   0   1   0   0   0   0   0   0]
 [  0   0  30   0   0   3   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0 238   0   0   0]
 [  0   0   0   0   0   5   0   0   0]
 [  0   0   0   0   0  11   0   0   0]
 [  0   0   0   0   0   5   0   0   0]]
                             precision    recall  f1-score   support

                 Allegories       0.00      0.00      0.00         1
          Christmas Stories       0.00      0.00      0.00         1
      Detective and Mystery       0.94      0.91      0.92        33
           Ghost and Horror       0.00      0.00      0.00         2
Humorous and Wit and Satire       0.00      0.00      0.00         2
                   Literary       0.89      1.00      0.94       238
           Love and Romance       0.00      0.00      0.00         5
          Sea and Adventure       0.00      0.00      0.00        11
            Western Storie

In [51]:
print('Misclassification Count :' ,count_misclassified)

Misclassification Count : 30


In [45]:
len(alldata_test)

298