In [ ]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
import numpy as np
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")

In [ ]:
doc2vec_train = pd.read_csv(r"/Users/surabhi/Desktop/ATML_Project/InitialDataPrep-FeatureExtractionPhase-May-2020/DataPreprocessed/Train_doc2vec.csv")

In [ ]:
doc2vec_test = pd.read_csv(r"/Users/surabhi/Desktop/ATML_Project/InitialDataPrep-FeatureExtractionPhase-May-2020/DataPreprocessed/Test_doc2vec.csv")

In [ ]:
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer 

In [ ]:
data = pd.concat ([doc2vec_train, doc2vec_test])

In [ ]:
enc1 = OneHotEncoder(handle_unknown='ignore')
enc_df1 = pd.DataFrame(enc1.fit_transform(data[['Book_Name']]).toarray())
 # merge with main df bridge_df on key values
del data['Book_Name']
col_name=[]
for i in range(enc_df1.columns.start,enc_df1.columns.stop,enc_df1.columns.step):
    x="Book_Name"+(str(i))
    col_name.append(x)
enc_df1.columns=col_name
data = data.join(enc_df1)

In [ ]:
enc1 = OneHotEncoder(handle_unknown='ignore')
enc_df1 = pd.DataFrame(enc1.fit_transform(data[['Author_Name']]).toarray())
 # merge with main df bridge_df on key values
del data['Author_Name']
col_name=[]
for i in range(enc_df1.columns.start,enc_df1.columns.stop,enc_df1.columns.step):
    x="Author_Name"+(str(i))
    col_name.append(x)
enc_df1.columns=col_name
data = data.join(enc_df1)

In [ ]:
data.head(3)

Content guten_genre       id  \
0  One day in the early June of the year 1900 I w...    Literary  pg37479   
0  Ben Hayle, keeper, stepped out of his rose-cov...    Literary  pg34244   
1  A solitary room at midnight: a single wax cand...    Literary  pg51715   

                                          clean_data  cnt  index         0  \
0   early year walk hampstead neighbourhood vale ...    1    330 -0.000547   
0   hayle keeper stepped cottage thoreby wood han...    1    620  0.001031   
1   solitary room midnight single candle lighted ...    1    376 -0.000750   

          1         2         3  ...  Author_Name496  Author_Name497  \
0  0.000713 -0.001372  0.000640  ...             0.0             0.0   
0 -0.000478 -0.000320 -0.001067  ...             0.0             0.0   
1  0.000750 -0.000054  0.000074  ...             0.0             0.0   

   Author_Name498  Author_Name499  Author_Name500  Author_Name501  \
0             0.0             0.0             0.0             0.0   
0             0.0             0.0             0.0             0.0   
1             0.0             0.0             0.0             0.0   

   Author_Name502  Author_Name503  Author_Name504  Author_Name505  
0             0.0             0.0             0.0             0.0  
0             0.0             0.0             0.0             0.0  
1             0.0             0.0             0.0             0.0  

[3 rows x 1804 columns]

In [ ]:
doc2vec_train = data[0:695]
len(doc2vec_train)

695

In [ ]:
doc2vec_test = data[696:]
len(doc2vec_test)

298

In [ ]:
del doc2vec_train['Content']
del doc2vec_train['clean_data']
del doc2vec_train['id']
del doc2vec_train['cnt']

In [ ]:
del doc2vec_train['index']

In [ ]:
del doc2vec_test['Content']
del doc2vec_test['id']
del doc2vec_test['clean_data']
del doc2vec_test['cnt']
del doc2vec_test['index']

In [ ]:
y_train = doc2vec_train['guten_genre']
y_test = doc2vec_test['guten_genre']

In [ ]:
del doc2vec_train['guten_genre']
del doc2vec_test['guten_genre']

In [ ]:
logreg = LogisticRegression(solver = 'lbfgs')
logreg.fit(doc2vec_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_pred = logreg.predict(doc2vec_test)

In [ ]:
count_misclassified = (y_test != y_pred).sum()

In [ ]:
from sklearn.metrics import accuracy_score, f1_score
from sklearn.metrics import classification_report, confusion_matrix

print('Testing accuracy %s' % accuracy_score(y_test, y_pred))
print('Testing F1 score: {}'.format(f1_score(y_test, y_pred, average='weighted')))


Testing accuracy 0.7919463087248322
Testing F1 score: 0.6999974863635221


In [ ]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0  33   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0   3   0   0   0]
 [  0   0   0   0   0 236   0   0   0]
 [  0   0   0   0   0   6   0   0   0]
 [  0   0   0   0   0  11   0   0   0]
 [  0   0   0   0   0   5   0   0   0]]
                             precision    recall  f1-score   support

                 Allegories       0.00      0.00      0.00         1
          Christmas Stories       0.00      0.00      0.00         1
      Detective and Mystery       0.00      0.00      0.00        33
           Ghost and Horror       0.00      0.00      0.00         2
Humorous and Wit and Satire       0.00      0.00      0.00         3
                   Literary       0.79      1.00      0.88       236
           Love and Romance       0.00      0.00      0.00         6
          Sea and Adventure       0.00      0.00      0.00        11
            Western Storie

In [ ]:
print('Misclassification Count :' ,count_misclassified)

Misclassification Count : 62
