In [ ]:
import warnings
warnings.filterwarnings("ignore")
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer 

In [ ]:
data = pd.read_csv(r"/Users/surabhi/Desktop/ATML_Project/InitialDataPrep-FeatureExtractionPhase-May-2020/DataPreprocessed/Preprocessed_stopword.csv")

In [ ]:
data.head(3)

Content  \
0  "Love seeketh only Self to please, To bind ano...   
1  To G. P. B. JAMES, Esq.\nDear James, - You, on...   
2              Tokyo To Tijuana: Gabriele Departi...   

                                      Book_Name guten_genre  \
0                              The Narrow House    Literary   
1               Roland Cashel- Volume I (of II)    Literary   
2  Tokyo to Tijuana: Gabriele Departing America    Literary   

                  Author_Name       id  \
0               Scott| Evelyn  pg42534   
1        Lever| Charles James  pg33468   
2  Sills| Steven David Justin  pg12733   

                                          clean_data  cnt  
0   bind delight joy loss ease build hell heaven ...    1  
1   dear time dedicated tale deep thrilling inscr...    1  
2   tokyo departing sill probable arrive city cle...    1

In [ ]:
enc1 = OneHotEncoder(handle_unknown='ignore')
enc_df1 = pd.DataFrame(enc1.fit_transform(data[['Book_Name']]).toarray())
 # merge with main df bridge_df on key values
del data['Book_Name']
col_name=[]
for i in range(enc_df1.columns.start,enc_df1.columns.stop,enc_df1.columns.step):
    x="Book_Name"+(str(i))
    col_name.append(x)
enc_df1.columns=col_name
data = data.join(enc_df1)

In [ ]:
enc1 = OneHotEncoder(handle_unknown='ignore')
enc_df1 = pd.DataFrame(enc1.fit_transform(data[['Author_Name']]).toarray())
 # merge with main df bridge_df on key values
del data['Author_Name']
col_name=[]
for i in range(enc_df1.columns.start,enc_df1.columns.stop,enc_df1.columns.step):
    x="Author_Name"+(str(i))
    col_name.append(x)
enc_df1.columns=col_name
data = data.join(enc_df1)

In [ ]:
alldata_train, alldata_test = train_test_split(data, test_size=0.3, random_state=42, stratify = np.array(data['guten_genre']))

In [ ]:
alldata_train.head(3)

In [ ]:
y_train = alldata_train['guten_genre']
y_test = alldata_test['guten_genre']

In [ ]:
del alldata_train['guten_genre']
del alldata_test['guten_genre']

In [ ]:
alldata_test.head()

Content       id  \
620  Ben Hayle, keeper, stepped out of his rose-cov...  pg34244   
131  There was a "scene" that evening at Ivy Lodge ...  pg35430   
30   "I'd far rather beg in the gutter than marry y...  pg39066   
963  The dark was falling over the court-room. A lu...  pg35326   
585  Hearing the sound of lightly-falling footsteps...  pg46566   

                                            clean_data  cnt  Book_Name0  \
620   hayle keeper stepped cottage thoreby wood han...    1         0.0   
131   scene evening lodge scene conducted genteel m...    1         0.0   
30    gutter flashed girl goaded clouded indignant ...    1         0.0   
963   dark falling lurid setting gleamed redly wind...    1         0.0   
585   hearing sound footstep captain melun ceased i...    1         0.0   

     Book_Name1  Book_Name2  Book_Name3  Book_Name4  Book_Name5  ...  \
620         0.0         0.0         0.0         0.0         0.0  ...   
131         0.0         0.0         0.0         0.0         0.0  ...   
30          0.0         0.0         0.0         0.0         0.0  ...   
963         0.0         0.0         0.0         0.0         0.0  ...   
585         0.0         0.0         0.0         0.0         0.0  ...   

     Author_Name496  Author_Name497  Author_Name498  Author_Name499  \
620             0.0             0.0             0.0             0.0   
131             0.0             0.0             0.0             0.0   
30              0.0             0.0             0.0             0.0   
963             0.0             0.0             0.0             0.0   
585             0.0             0.0             0.0             0.0   

     Author_Name500  Author_Name501  Author_Name502  Author_Name503  \
620             0.0             0.0             0.0             0.0   
131             0.0             0.0             0.0             0.0   
30              0.0             0.0             0.0             0.0   
963             0.0             0.0             0.0             0.0   
585             0.0             0.0             0.0             0.0   

     Author_Name504  Author_Name505  
620             0.0             0.0  
131             0.0             0.0  
30              0.0             0.0  
963             0.0             0.0  
585             0.0             0.0  

[5 rows x 1502 columns]

In [ ]:
vectorizer = TfidfVectorizer(sublinear_tf=True)
X_train = vectorizer.fit_transform(alldata_train['clean_data'])

In [ ]:
X_test = vectorizer.transform(alldata_test['clean_data'])

In [ ]:
X_train.shape

(695, 112257)

In [ ]:
X_test.shape

(299, 112257)

In [ ]:
feature_names = vectorizer.get_feature_names()

In [ ]:
len(feature_names)

112257

In [ ]:
feature_names

['aachen',
 'aaem',
 'aair',
 'aalsund',
 'aamand',
 'aamy',
 'aamænd',
 'aaoow',
 'aaraaf',
 'aargau',
 'aarhus',
 'aase',
 'aback',
 'abaddon',
 'abaft',
 'abaho',
 'abaht',
 'abalone',
 'abana',
 'abandon',
 'abandoned',
 'abandonedly',
 'abandoning',
 'abandonment',
 'abanijo',
 'abart',
 'abase',
 'abased',
 'abasement',
 'abash',
 'abashed',
 'abashes',
 'abashing',
 'abashingly',
 'abashment',
 'abasing',
 'abate',
 'abated',
 'abatement',
 'abates',
 'abating',
 'abatis',
 'abatross',
 'abattez',
 'abattis',
 'abattoir',
 'abattre',
 'abawt',
 'abazzia',
 'abbaside',
 'abbassieh',
 'abbate',
 'abbati',
 'abbatial',
 'abbaye',
 'abbe',
 'abbencombe',
 'abberley',
 'abbess',
 'abbetting',
 'abbeville',
 'abbey',
 'abbeyland',
 'abbia',
 'abbot',
 'abbotsbury',
 'abbotsford',
 'abbott',
 'abbotts',
 'abbozzatore',
 'abbrazza',
 'abbreviate',
 'abbreviated',
 'abbreviating',
 'abbreviation',
 'abbreviative',
 'abbrucia',
 'abbé',
 'abbés',
 'abc',
 'abcdef',
 'abdallah',
 'abdera',

In [ ]:
alldata_train.to_csv(r"/Users/surabhi/Desktop/ATML_Project/InitialDataPrep-FeatureExtractionPhase-May-2020/DataPreprocessed/Train_tfidf.csv", header = True, index = False)

In [ ]:
alldata_test.to_csv(r"/Users/surabhi/Desktop/ATML_Project/InitialDataPrep-FeatureExtractionPhase-May-2020/DataPreprocessed/Test_tfidf.csv", header = True, index = False)

In [ ]:
logreg = LogisticRegression(solver = 'lbfgs')
logreg.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred = logreg.predict(X_test)

In [ ]:
count_misclassified = (y_test != y_pred).sum()

In [ ]:
from sklearn.metrics import accuracy_score, f1_score
from sklearn.metrics import classification_report, confusion_matrix

print('Testing accuracy %s' % accuracy_score(y_test, y_pred))
print('Testing F1 score: {}'.format(f1_score(y_test, y_pred, average='weighted')))

Testing accuracy 0.7993311036789298
Testing F1 score: 0.7133758709893381


In [ ]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   1   0   0  32   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0   2   0   0   0]
 [  0   0   0   0   0 238   0   0   0]
 [  0   0   0   0   0   5   0   0   0]
 [  0   0   0   0   0  11   0   0   0]
 [  0   0   0   0   0   5   0   0   0]]
                             precision    recall  f1-score   support

                 Allegories       0.00      0.00      0.00         1
          Christmas Stories       0.00      0.00      0.00         2
      Detective and Mystery       1.00      0.03      0.06        33
           Ghost and Horror       0.00      0.00      0.00         2
Humorous and Wit and Satire       0.00      0.00      0.00         2
                   Literary       0.80      1.00      0.89       238
           Love and Romance       0.00      0.00      0.00         5
          Sea and Adventure       0.00      0.00      0.00        11
            Western Storie

In [ ]:
print('Misclassification Count :' ,count_misclassified)

Misclassification Count : 60


In [ ]:
from sklearn.feature_selection import chi2, SelectKBest
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics
from sklearn.naive_bayes import MultinomialNB

In [ ]:
k = [10000, 25000, 50000, 75000, 100000]
clf = LogisticRegression(solver = 'lbfgs')
ch, inferences, trained_model, accu = [], [], [], []
x_feat_train, x_feat_test = [], []

for i in range(0, len(k)):
    ch.append(SelectKBest(chi2, k[i]))
    x_feat_train.append(ch[i].fit_transform(X_train, y_train))
    x_feat_test.append(ch[i].transform(X_test))
    trained_model.append(clf.fit(x_feat_train[i], y_train))
    inferences.append(trained_model[i].predict((x_feat_test[i])))
    accu.append(metrics.f1_score(y_test, inferences[i], average='macro'))
    print('For K value:', k[i],'The F1 Score is',accu[i])

For K value: 10000 The F1 Score is 0.09848955100351749
For K value: 25000 The F1 Score is 0.09848955100351749
For K value: 50000 The F1 Score is 0.09848955100351749
For K value: 75000 The F1 Score is 0.10520924787825577
For K value: 100000 The F1 Score is 0.10520924787825577


In [ ]:
k = [10000, 25000, 50000, 75000, 100000]
clf = MultinomialNB(alpha=0.001)
ch, inferences, trained_model, accu = [], [], [], []
x_feat_train, x_feat_test = [], []

for i in range(0, len(k)):
    ch.append(SelectKBest(chi2, k[i]))
    x_feat_train.append(ch[i].fit_transform(X_train, y_train))
    x_feat_test.append(ch[i].transform(X_test))
    trained_model.append(clf.fit(x_feat_train[i], y_train))
    inferences.append(trained_model[i].predict((x_feat_test[i])))
    accu.append(metrics.f1_score(y_test, inferences[i], average='macro'))
    print('For K value:', k[i],'The F1 Score is',accu[i])

For K value: 10000 The F1 Score is 0.25474867193428863
For K value: 25000 The F1 Score is 0.26906895973833095
For K value: 50000 The F1 Score is 0.27390109890109887
For K value: 75000 The F1 Score is 0.2822286572286572
For K value: 100000 The F1 Score is 0.2822286572286572
